spring:
  application:
    name: SB-13-Security-OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 50584024642-r9ckb17k7skgpsl96gqrcgdfebjragdc.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: Ov23linPKkXuOG3VNzWN
            client-secret: 0a826a60d71367eff339bee76c78ec4daa5abfbf
