spring:
  application:
    name: SB-13-Security-OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '{google-client-id}'
            client-secret: '{google-client-secret}'
          github:
            client-id: '{github-client-id}'
            client-secret: '{github-client-secret}'
